# Wybierz obraz bazowy z CUDA i PyTorch
FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime AS base

# Instalacja zależności systemowych
RUN apt update && apt install -y \
        build-essential \
        python3-dev \
        pkg-config \
        git \
    && apt clean

# Ustawienie katalogu roboczego
WORKDIR /home/user/autoencoders

# Instalacja pakietów pythona
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Instalacja hooków
COPY .pre-commit-config.yaml .
COPY .git .git
RUN pre-commit install --install-hooks

# Tworzenie użytkownika
ENV UID=1001 GID=1001
RUN addgroup --gid ${GID} --system user && \
    adduser --shell /bin/bash --disabled-password --uid ${UID} --system --group user

# Konfiguracja końcowa
USER user
ENTRYPOINT ["bash"]
