# Wybierz obraz bazowy z CUDA i PyTorch
FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime AS base

# Instalacja zależności systemowych
RUN apt update && apt install -y \
    build-essential \
    python3-dev \
    pkg-config \
    git \
    && apt clean

# Ustawienie katalogu roboczego
WORKDIR /home/user/autoencoders

# Instalacja pakietów pythona
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Instalacja pakietów pythona niezbęddnych do automatyzacji
RUN pip install --no-cache-dir \
    black \
    black[jupyter] \
    codespell \
    pyupgrade \
    pre-commit

# Instalacja pipx i poetry
RUN python3 -m pip install --user pipx && \
    python3 -m pipx ensurepath && \
    python3 -m pipx completions && \
    python3 -m pipx install poetry

RUN echo "eval \"\$(register-python-argcomplete pipx)\"" >> ~/.bashrc

# Tworzenie użytkownika
ENV UID=1001 GID=1001
RUN addgroup --gid ${GID} --system user && \
    adduser --shell /bin/bash --disabled-password --uid ${UID} --system --group user

# Konfiguracja końcowa
USER user
ENTRYPOINT ["sh", "-c", "pre-commit install --install-hooks && exec bash"]
